#!/bin/bash
#PBS -l walltime=1:00:00
#PBS -l mem=192GB
#PBS -l ncpus=48
#PBS -l jobfs=10GB
#PBS -l storage=gdata/hh5+gdata/er8+scratch/er8+gdata/rv74+gdata/rt52
#PBS -l other=hyperthread
#PBS -q normal
#PBS -P er8
#PBS -o /home/548/cd3022/Irradiance-comparisons
#PBS -j oe
module use /g/data3/hh5/public/modules
module load conda/analysis3
conda
python3 /home/548/cd3022/Irradiance-comparisons/himawari-era5.py