#!/bin/bash 
#PBS -l walltime=1:00:00 
#PBS -l mem=96GB 
#PBS -l ncpus=48 
#PBS -l jobfs=10GB 
#PBS -l storage=gdata/xp65+gdata/er8+gdata/ob53+gdata/rt52+gdata/rv74+gdata/su28+scratch/er8 
#PBS -l other=hyperthread 
#PBS -q normal 
#PBS -P er8 
#PBS -o /home/548/cd3022/repos/Irradiance-comparisons/logs/001_calc_hourly_months_himawari_2016-5.oe 
#PBS -j oe 
cd /home/548/cd3022/repos/Irradiance-comparisons 
source ./env.sh 
python3 scripts/001_calc_hourly_months.py himawari 2016 5
