#!/bin/bash 
#PBS -l walltime=1:00:00 
#PBS -l mem=96GB 
#PBS -l ncpus=24 
#PBS -l jobfs=10GB 
#PBS -l storage=gdata/xp65+gdata/er8+gdata/ob53+gdata/rt52+gdata/rv74+gdata/su28+scratch/er8 
#PBS -l other=hyperthread 
#PBS -q normal 
#PBS -P er8 
#PBS -o /home/548/cd3022/repos/Irradiance-comparisons/logs/00_calc_hourly_himawari_2024.oe 
#PBS -j oe 
cd /home/548/cd3022/repos/Irradiance-comparisons 
source ./env.sh 
python3 scripts/00_calc_hourly.py himawari 2024
