#!/bin/bash 
#PBS -l walltime=1:00:00 
#PBS -l mem=50GB 
#PBS -l ncpus=24 
#PBS -l jobfs=10GB 
#PBS -l storage=gdata/xp65+gdata/er8+gdata/ob53+gdata/rt52+gdata/rv74 
#PBS -l other=hyperthread 
#PBS -q normal 
#PBS -P er8 
#PBS -o /home/548/cd3022/repos/Irradiance-comparisons/job_log.oe 
#PBS -j oe 

cd /home/548/cd3022/repos/Irradiance-comparisons

source ./env.sh

python3 scripts/calc_monthly.py barra-c2 monthly